import { parseArtifactManifest, type ArtifactManifest, type EvidenceRecord } from "../domain/artifact";

function digest(text: string): string { let h = 0x811c9dc5; for (let i = 0; i < text.length; i += 1) { h ^= text.charCodeAt(i); h = Math.imul(h, 0x01000193); } return `fnv1a32:${(h >>> 0).toString(16).padStart(8, "0")}`; }
function evidence(id: string, locator: string, content: string): EvidenceRecord { return { id, sourceId: "src-capt-weekly", locator: { kind: "line", value: locator }, contentDigest: digest(content), content, extraction: "parsed" }; }

const manifest: ArtifactManifest = {
  schemaVersion: "1.0.0",
  project: { id: "project-capt-weekly-2026-08-19", name: "CAPT Core — August 19 Evidence Brief", createdAt: "2026-08-19T16:29:00-05:00", updatedAt: "2026-08-19T16:29:00-05:00" },
  sources: [{ id: "src-capt-weekly", name: "CAPT Weekly Brief shared conversation", mediaType: "text/plain", digest: "sha256:2bcf85fd175edfaa03662f196c84f528e2a73803f7875635945af0e79949507a", byteSize: 13593, origin: "chatgpt_share", parseState: "parsed", locatorCapabilities: ["line"] }],
  evidence: [
    evidence("ev-main", "Main convergence paragraph", "Main commit: 4a2eddbf0dbd09b976e2c890ce6f704db3fce8cf."),
    evidence("ev-pr117", "PR #117 paragraph", "PR #117 branch integration/capt-core-terminal-convergence-r2 head 5c0bdf02a3eb6d20cb4c33b0ad3ec517a0d11689."),
    evidence("ev-pr118", "PR #118 provider correction paragraph", "PR #118 provider correction head 0dbb9fa467127830089763a22723f44c744ba335."),
    evidence("ev-tests-python", "PR #117 exact-head evidence", "Python exact-head: 1096 passed, 13 skipped, 12 deselected, 0 failed."),
    evidence("ev-tests-swift", "PR #117 exact-head evidence", "Swift exact-head: 63 tests, 7 deliberate opt-in skips, 0 failures."),
    evidence("ev-tests-mcp", "MCP companion evidence", "MCP companion: 259 tests PASS."),
    evidence("ev-security", "Security Closure Cockpit", "Security Closure Cockpit: PASS 0, FAIL 0, NOT_VERIFIED 21, N/A 26, releaseAuthorized:false."),
    evidence("ev-installed", "Installed source identity paragraph", "Installed regular CAPT source marker points to PR #118-era code installed about 10:19:36–10:19:37 CDT."),
    evidence("ev-runtime", "Running RuntimeService identity paragraph", "Running RuntimeService started about 05:30:56 CDT, before the PR #118-era install; installed source identity is therefore not proof of running process identity.")
  ],
  datasets: [
    { id: "ds-test-evidence", name: "Exact-head verification evidence", sourceIds: ["src-capt-weekly"], columns: [{ id: "suite", label: "Suite", type: "category" }, { id: "passed", label: "Passed", type: "integer", unit: "tests" }, { id: "skipped", label: "Skipped", type: "integer", unit: "tests" }, { id: "deselected", label: "Deselected", type: "integer", unit: "tests" }, { id: "failed", label: "Failed", type: "integer", unit: "tests" }], rows: [{ suite: "Python", passed: 1096, skipped: 13, deselected: 12, failed: 0 }, { suite: "Swift", passed: 63, skipped: 7, deselected: 0, failed: 0 }, { suite: "MCP", passed: 259, skipped: 0, deselected: 0, failed: 0 }], rowCount: 3, representedRowCount: 3, missingness: { suite: 0, passed: 0, skipped: 0, deselected: 0, failed: 0 }, storage: { strategy: "inline" } },
    { id: "ds-security-closure", name: "Security Closure Cockpit", sourceIds: ["src-capt-weekly"], columns: [{ id: "status", label: "Status", type: "category" }, { id: "controls", label: "Controls", type: "integer", unit: "controls" }], rows: [{ status: "PASS", controls: 0 }, { status: "FAIL", controls: 0 }, { status: "NOT_VERIFIED", controls: 21 }, { status: "N/A", controls: 26 }], rowCount: 4, representedRowCount: 4, missingness: { status: 0, controls: 0 }, storage: { strategy: "inline" } },
    { id: "ds-release-lineage", name: "Convergence lineage", sourceIds: ["src-capt-weekly"], columns: [{ id: "stage", label: "Stage", type: "category" }, { id: "ref", label: "Ref", type: "string" }, { id: "state", label: "State", type: "category" }], rows: [{ stage: "main", ref: "4a2eddbf0dbd09b976e2c890ce6f704db3fce8cf", state: "merged" }, { stage: "terminal convergence", ref: "5c0bdf02a3eb6d20cb4c33b0ad3ec517a0d11689", state: "candidate" }, { stage: "provider correction", ref: "0dbb9fa467127830089763a22723f44c744ba335", state: "correction" }], rowCount: 3, representedRowCount: 3, missingness: { stage: 0, ref: 0, state: 0 }, storage: { strategy: "inline" } },
    { id: "ds-runtime-identity", name: "Installed vs running identity", sourceIds: ["src-capt-weekly"], columns: [{ id: "event", label: "Event", type: "category" }, { id: "time", label: "Observed time", type: "string" }], rows: [{ event: "RuntimeService start", time: "05:30:56 CDT" }, { event: "PR #118-era install", time: "10:19:36–10:19:37 CDT" }], rowCount: 2, representedRowCount: 2, missingness: { event: 0, time: 0 }, storage: { strategy: "inline" } }
  ],
  claims: [
    { id: "claim-tests", text: "Exact-head verification recorded 1,096 passing Python tests, 63 Swift tests, and 259 passing MCP companion tests with zero reported failures in those cited runs.", epistemicStatus: "fact", claimType: "descriptive_fact", confidence: 1, evidenceIds: ["ev-tests-python", "ev-tests-swift", "ev-tests-mcp"], datasetIds: ["ds-test-evidence"], caveats: ["Suite sizes are not directly comparable measures of subsystem quality."], contradictionStatus: "none", publishable: true },
    { id: "claim-release-authorization", text: "Security Closure Cockpit reports releaseAuthorized:false with PASS 0, FAIL 0, NOT_VERIFIED 21, and N/A 26.", epistemicStatus: "fact", claimType: "descriptive_fact", confidence: 1, evidenceIds: ["ev-security"], datasetIds: ["ds-security-closure"], caveats: ["Zero FAIL does not imply release readiness when 21 controls remain NOT_VERIFIED."], contradictionStatus: "none", publishable: true },
    { id: "claim-runtime-identity-gap", text: "The installed PR #118-era source identity is not sufficient evidence of the currently running RuntimeService identity because the observed process predates that install.", epistemicStatus: "derived", claimType: "derived_metric", confidence: 1, evidenceIds: ["ev-installed", "ev-runtime", "ev-pr118"], datasetIds: ["ds-runtime-identity"], formula: "process_start_at < install_at => runtime_identity_not_proven_equal_to_installed_source", caveats: ["This is a runtime-upgrade/restart verification gap, not proof that the source hardening is defective."], contradictionStatus: "none", publishable: true },
    { id: "claim-convergence", text: "CAPT Core has strong convergence evidence while release authority remains incomplete.", epistemicStatus: "inference", claimType: "model_interpretation", confidence: 0.96, evidenceIds: ["ev-pr117", "ev-pr118", "ev-tests-python", "ev-tests-swift", "ev-tests-mcp", "ev-security"], datasetIds: ["ds-test-evidence", "ds-security-closure", "ds-release-lineage"], caveats: ["Convergence evidence and release authorization answer different questions."], contradictionStatus: "none", publishable: true }
  ],
  visuals: [
    { id: "visual-tests", title: "Verified execution volume by suite", family: "bar", analyticalJob: "comparison", datasetId: "ds-test-evidence", claimIds: ["claim-tests"], evidenceIds: ["ev-tests-python", "ev-tests-swift", "ev-tests-mcp"], encodings: { x: "suite", y: "passed" }, annotations: [{ text: "Counts show executions, not cross-suite quality scores.", claimId: "claim-tests" }], filters: {}, accessibleSummary: "Python shows 1,096 passing tests, Swift 63 tests, and MCP 259 passing tests; all cited runs report zero failures." },
    { id: "visual-security", title: "Security closure is mostly unresolved, not failed", family: "status", analyticalJob: "composition", datasetId: "ds-security-closure", claimIds: ["claim-release-authorization"], evidenceIds: ["ev-security"], encodings: { category: "status", value: "controls" }, annotations: [{ text: "21 controls remain NOT_VERIFIED.", claimId: "claim-release-authorization" }], filters: {}, accessibleSummary: "Security controls: 0 pass, 0 fail, 21 not verified, 26 not applicable. Release authorization is false." },
    { id: "visual-lineage", title: "Convergence lineage", family: "table", analyticalJob: "table_lookup", datasetId: "ds-release-lineage", claimIds: ["claim-convergence"], evidenceIds: ["ev-main", "ev-pr117", "ev-pr118"], encodings: { columns: "stage,ref,state" }, annotations: [], filters: {}, accessibleSummary: "Lineage runs from current main to terminal convergence PR 117 and provider correction PR 118." },
    { id: "visual-runtime", title: "Installed source ≠ proven running process", family: "table", analyticalJob: "table_lookup", datasetId: "ds-runtime-identity", claimIds: ["claim-runtime-identity-gap"], evidenceIds: ["ev-installed", "ev-runtime"], encodings: { columns: "event,time" }, annotations: [{ text: "Restart and re-probe before claiming runtime identity.", claimId: "claim-runtime-identity-gap" }], filters: {}, accessibleSummary: "The running service started around 05:30:56 CDT and the PR 118-era install occurred around 10:19:36 to 10:19:37 CDT." }
  ],
  auditEvents: [],
  warnings: [],
  exportMetadata: { generatedAt: "2026-08-19T16:29:00-05:00", generator: "InfoGenius Evidence Studio", formatVersion: "1.0.0" }
};

export const CAPT_WEEKLY_BRIEF_MANIFEST = parseArtifactManifest(manifest);
